### ISSUE TITLE
Data source issue [NIST Library]: Missing bibliographic information for NBS SP 500-20 (1977)

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-nist#14]
From https://github.com/relaton/relaton-data-nist/issues/6#issuecomment-1171190156 the IETF has a bibliographic reference to NBS SP 500-20 (1980):

(this is clearly a mistaken file name)
```
reference.FIPS.500-20.1977.xml
```

This document exists on the NIST CSRC site, but is not available in the Tech Pubs dataset.

CSRC:
https://csrc.nist.gov/publications/detail/sp/500-20/archive/1980-09-01

And the PDF is available here:
https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nbsspecialpublication500-20e1980.pdf

<img width="528" alt="Screenshot 2022-07-01 at 1 05 51 AM" src="https://user-images.githubusercontent.com/11865/176725359-d47a30bf-31d4-4f74-9c9a-f785b6f317e3.png">

**Comment by ronaldtse** [comment]
Thanks to @kmiller621 for pointing this out in https://github.com/usnistgov/NIST-Tech-Pubs/issues/29. The correct information is:

```
Report Number: NBS SP 500-20e1980
doi:10.6028/NBS.SP.500-20e1980
```

<img width="719" alt="Screenshot 2022-07-06 at 8 52 02 PM" src="https://user-images.githubusercontent.com/11865/177543952-54d5b222-bd45-4ac3-81a1-96ba2c16c578.png">

**Comment by ronaldtse** [comment]
@andrew2net how are we dealing with the document identifiers that are duplicated with only edition year differences? Why is this entry not available in relaton-data-nist?

**Comment by andrew2net** [comment]
@ronaldtse the document can be fetched with `NBS SP 500-20e1977` reference
```
relaton fetch 'NBS SP 500-20e1977'
[relaton-nist] ("NBS SP 500-20e1977") fetching...
[relaton-nist] ("NBS SP 500-20e1977") found SP 500-20
<bibdata type="standard">
  <fetched>2022-08-08</fetched>
...
```

**Comment by ronaldtse** [comment]
@andrew2net but it fetches the wrong document. 
There are two documents:
* "NBS SP 500-20e1977"
* "NBS SP 500-20e1980"

```sh
$ relaton fetch 'NBS SP 500-20e1977'
[relaton-nist] ("NBS SP 500-20e1977") fetching...
[relaton-nist] ("NBS SP 500-20e1977") found SP 500-20
<bibdata type="standard">
  <fetched>2022-08-09</fetched>
  <title format="text/plain" language="en" script="Latn">Validating the Correctness of Hardware Implementations of the NBS Data Encryption Standard</title>
  <uri type="src">https://csrc.nist.gov/publications/detail/sp/500-20/archive/1980-09-01</uri>
  <uri type="doi">https://doi.org/10.6028/NBS.SP.500-20e1980</uri>
  <docidentifier type="NIST" primary="true">SP 500-20</docidentifier>
```

You can see in the DOI it is fetching the `NBS.SP.500-20e1980` document.

If we use pubid-nist we can resolve this issue?

**Comment by andrew2net** [comment]
@ronaldtse Yes, this gem parses parts of a reference and uses the parts to select documents. It seems the reference parser needs to be fixed. I think instead of fixing the current implementation it'd be better to spend time on pubid-nist integration.

**Comment by andrew2net** [comment]
It works correctly with relaton-nist v1.19.1
```sh
$ relaton fetch 'NBS SP 500-20e1977'
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
[relaton-nist] Downloaded index from https://raw.githubusercontent.com/relaton/relaton-data-nist/main/index-v1.zip
<bibdata type="standard" schema-version="v1.2.9">
  <fetched>2024-07-30</fetched>
  <title type="main" format="text/plain" language="en" script="Latn">Validating the correctness of hardware implementations of the NBS data encryption standard</title>
  <uri type="doi">https://doi.org/10.6028/NBS.SP.500-20e1977</uri>
  <docidentifier type="NIST" primary="true">NBS SP 500-20e1977</docidentifier>
  <docidentifier type="DOI">10.6028/NBS.SP.500-20e1977</docidentifier>
```
