### ISSUE TITLE
Update to 2024-11 release

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-nist#27]
As described in:
* https://github.com/usnistgov/NIST-Tech-Pubs/releases/tag/Nov2024

**Comment by andrew2net** [comment]
Updated in v1.19.7
@ronaldtse BTW @mico is implementing fetching IDs and titles from allrecords-MODS.xml in pubid-nist. When it is implemented we will need to update the URL in pubid-nist. We can reuse in relaton-nist the URL defined in pubid-nist.
